server:
    port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/palmap_service_platform2?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1986322asdf
    driver-class-name: com.mysql.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
  activemq:
    broker-url: failover:(tcp://127.0.0.1:61616,tcp://127.0.0.1:61617)
    in-memory: true
    pooled: false
  jms:
    pub-sub-domain: false
  redis:
    cluster:
      nodes:
        - 139.129.46.39:7000
        - 139.129.46.39:7001

logging:
  config: classpath:log4j2.xml