server:
    port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datasource?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
  activemq:
    broker-url: failover:(tcp://127.0.0.1:61616,tcp://127.0.0.1:61617)
    in-memory: true
    pooled: false
  jms:
    pub-sub-domain: false
  redis:
    cluster:
      nodes:
        - 192.168.0.1:6379
        - 192.168.0.2:6379

logging:
  config: classpath:log4j2.xml

