package com.github.rpc.grpc.customRPC.test;

import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;

/**
 * Created by zk_chs on 16/6/27.
 */
public class Consumer {

    public static void main(String[] args) throws IOException {
        Socket socket = new Socket("127.0.0.1", 1234);
        ObjectOutputStream output = new ObjectOutputStream(socket.getOutputStream());
        output.writeUTF("abcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkd");
        System.out.println("abcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkdabcdasdjaksdaskjdhasjkhdjkashdjkashdjkashdjkashdjkasjdhajksdhajskdhajskdhasjkdjashdjkajsdhjaksdjhasjkdashjdkasjdhasjkd".length());
        output.writeUTF("abcdf");
        output.close();
        socket.close();
    }

}
